### ISSUE TITLE
[Bug] Testing Submission Via URL

### ISSUE THREAD

**Issue by Akshay0701** [david-allison-1/actions-playground#1]
### **Is your feature request related to a problem? Please describe.**
AnkiDesktop have feature of "Paste Clipboard Image As PNG " in the preference window ,
currently AnkiDroid do support to copy and paste image but not have this preference option in app.

![Capture](https://user-images.githubusercontent.com/52353967/116271252-7041da00-a79d-11eb-9324-eae83f1a6027.PNG)

**Comment by david-allison** [comment]
Thanks!
